image: perl

stages:
  - test
  - release

test:
    stage: test
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
    script:
      - minil test 

release_staging:
    stage: release
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
      - echo "user $CPAN_USER" > /builds/cynovg/WG-API/pause
      - echo "password $CPAN_PASSWORD" >> /builds/cynovg/WG-API/pause
      - cat /builds/cynovg/WG-API/pause
    script:
      - echo | minil release
    only:
      - build