image: perl

stages:
  - test
  - release

test:
    stage: test
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
    script:
      - minil test
    except:
      - master

release_staging:
    stage: release
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
      - echo "user $CPAN_USER" > /tmp/pause
      - echo "password $CPAN_PASSWORD" >> /tmp/pause
      - git config --global user.email "cynovg@gmail.com"
      - git config --global user.name "Cyrill Novgorodcev"
    script:
      - echo -ne "\ny\n" | minil release
    only:
      - master