image: perl

stages:
  - build
  - release

build_staging:
    stage: build
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
    script:
      - minil test
    only:
      - build

release_staging:
    stage: release
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
      - echo "user $CPAN_USER" > /tmp/pause
      - echo "password $CPAN_PASSWORD" >> /tmp/pause
    script:
      - echo -ne "\ny\n" | minil release
    only:
      - master