image: perl

stages:
  - test
  - release

test:
    stage: test
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
    script:
      - minil test 

release_staging:
    stage: release
    before_script:
      - perl -V
      - cpan install App::cpm
      - cpm install -g
      - cpm install Minilla -g
      - cpm install Version::Next
      - echo "user $CPAN_USER" > ~/.pause
      - echo "password $CPAN_PASSWORD" >> ~/.pause
    script:
      - echo | minil release
    only:
      - master