language: perl
perl:
  - "5.27.1"
matrix:
  include:
    - perl: 5.20.2
      env: WGMODE=dev WG_KEY=8d6d512ab2061e3710acf09114e74661 COVERAGE=1
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm Minilla
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - minil install
before_script:
  - coverage-setup
script:
  - prove -l $(test-files)   # 
after_success:
  - coverage-report
